# Generated by Django 6.0.3 on 2026-04-06 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documentrecord',
            new_name='enterprise__tenant__01b018_idx',
            old_name='enterprise__tenant__0f6037_idx',
        ),
        migrations.RenameIndex(
            model_name='documentrecord',
            new_name='enterprise__tenant__1550ec_idx',
            old_name='enterprise__tenant__ff4c79_idx',
        ),
        migrations.RenameIndex(
            model_name='documentrecord',
            new_name='enterprise__tenant__0d0426_idx',
            old_name='enterprise__tenant__004d4a_idx',
        ),
    ]
