# Generated by Django 6.0.3 on 2026-04-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_documents', '0005_taxserviceprofile_certificate_password_encrypted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrecord',
            name='status',
            field=models.CharField(choices=[('recibido', 'Recibido'), ('en_cola', 'En cola'), ('procesando', 'Procesando'), ('valido', 'Valido'), ('con_error', 'Con error'), ('pdf_generado', 'PDF generado')], default='recibido', max_length=32),
        ),
    ]
