# Generated by Django 6.0.3 on 2026-04-08 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_documents', '0007_revokedtoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='revokedtoken',
            new_name='enterprise__token_t_0892ce_idx',
            old_name='enterprise_d_token_t_9e2554_idx',
        ),
    ]
